### ISSUE TITLE
Missing argument label 'strategy:' in call errors on build of 0.32.1

### ISSUE THREAD

**Issue by semirteskeredzic** [clerk/clerk-ios#101]
Hi Mike,

Hope you are doing great.

I'm getting two errors on build when I updated to 0.32.1:

/SourcePackages/checkouts/clerk-ios/Sources/UI/Components/Auth/SignUp/SignUpEmailCodeView.swift:63:50 Missing argument label 'strategy:' in call

/SourcePackages/checkouts/clerk-ios/Sources/UI/Components/Auth/SignUp/SignUpPhoneCodeView.swift:63:50 Missing argument label 'strategy:' in call

Error also appears on 0.32.0 but doesn't appear on 0.31.0

I am using:
Xcode Version 15.4 (15F31d)
iOS Deployment target 17.0

**Comment by mikepitre** [comment]
Hey @semirteskeredzic, thanks for letting me know! This is fixed in 0.32.2. When we're ready to move the clerk sdk to beta we'll have CI setup to avoid these little missed issues. Sorry about that!
