### ISSUE TITLE
Help with OAuth SwiftUI iOS Clerk

### ISSUE THREAD

**Issue by madebyshaurya** [clerk/clerk-ios#117]
Hey, I need help setting up OAuth (Sign in with Google) for my swiftui app. If anyone has done this before please provide a sample code or demo would be super useful since there isn't much resources on this online. Thanks.

**Comment by mikepitre** [comment]
Hey @madebyshaurya! The docs [here](https://clerk.com/docs/quickstarts/ios) and [here](https://clerk.com/docs/custom-flows/oauth-connections) should help you get up and running with OAuth.

If you're using SwiftUI, and you are using the shared `Clerk` object  as an `@ObservedObject`, once you successfully complete OAuth via the code snippet below, you should have a `session`.
```
try await SignIn
  .create(strategy: .oauth(.google))
  .authenticateWithRedirect()
```

**Comment by madebyshaurya** [comment]
Alright, thanks!
