### ISSUE TITLE
CocoaPods support?

### ISSUE THREAD

**Issue by tuantvu** [clerk/clerk-ios#55]
Will there be support for CocoaPods in addition to Swift Package Manager?

**Comment by mikepitre** [comment]
Hi @tuantvu, can you tell me a little bit about your use case that requires Cocoapods? You should be able to use cocoapods alongside SPM in project.

**Comment by tuantvu** [comment]
My particular use case is for a Flutter Plugin on top of the Clerk IOS SDK, which is only able to use Cocoapods for dependency management [at the moment](https://github.com/flutter/flutter/issues/126005). I tried including the ClerkSDK source code into the Flutter plugin, but did not think working through all additional dependency issues is worth it, especially in the long term. 

I thought this SDK would get more reach if it also supported Cocoapods. I wasn't aware IOS projects can use both at the same time. If that's the case, then it may not be worth it to support Cocoapods just for my Flutter use case, especially since your team now has a Flutter SDK in the roadmap.

**Comment by mikepitre** [comment]
Hey Tuan, while Cocoapods support isn't in the immediate plans given the reasons stated above, it may be something we explore to help enable Flutter support in the near future.
