### ISSUE TITLE
Question: How to obtain a JWT token to send to backend?

### ISSUE THREAD

**Issue by tuantvu** [clerk/clerk-ios#59]
I've attempted to scan the codebase, but did not see anything obvious about obtaining a JWT token for authorizing calls to my backend API. In React, this would be like using the `useAuth()`.getToken() function. Does this capability exists yet? If so, please provide documentation. Thanks

**Comment by semirteskeredzic** [comment]
You can get the token by accessing clerk.session.getToken() the method is mentioned here: [https://swiftpackageindex.com/clerk/clerk-ios/main/documentation/clerksdk/session](https://swiftpackageindex.com/clerk/clerk-ios/main/documentation/clerksdk/session)

**Comment by mikepitre** [comment]
Thanks @semirteskeredzic.

@tuantvu one clarifying note, you don't necessarily need to use `@ObservedObject` unless you are using SwiftUI or want to observe the lifecycle state stored for you by the ClerkSDK. You could also just manually fetch a token like so:
```
let token = Clerk.shared.session?.getToken()
```

**Comment by tuantvu** [comment]
@mikepitre @semirteskeredzic Two follow up questions:

I saw how `startSessionTokenPolling` is continuously getting a new token every 50 seconds and caching it. There is documentation saying the token only lives for 60 seconds. This is fine with me, but I am wondering why the TTL is not determined by the settings a client would configure in the Clerk Dashboard for JWT tokens?

2nd question, I'm curious how refresh tokens work? I was unable to find storing or refresh token exchange endpoint calls. We want to implement the ability for the user to authenticate with their face or fingerprint id on subsequent log ins after initial log in via social provider like Google or through email/password.

**Comment by mikepitre** [comment]
1. All Clerk short lived sessions tokens have a TTL of 60 seconds. The lifetime you're able to set via the dashboard is for the long lived refresh token.
2. The long lived token is included with every subsequent request once it is acquired on the creation of a client (device). It is used to obtain the short lived refresh tokens via the `session.getToken()` which is what is called via the polling you mentioned.

**Comment by tuantvu** [comment]
Thanks @mikepitre. Do you have any advice on how to implement my requirement above for face id/fingerprint log in? Does Clerk offer a solution for the requirement out of the box via configs somehow? My thought right now is to implement biometric checks in my app and showing it after confirming that the client and session exists after calling Clerk.load().

**Comment by mikepitre** [comment]
The SDK is still in alpha so all of this is subject to change, but yes the [ClerkSDK can handle this for you](https://github.com/clerk/clerk-ios/blob/main/Sources/API/Utils/LocalAuth.swift). 

When a user signs up or signs in with identifier + password, you can save their credentials behind biometry access with:
```
try Clerk.LocalAuth.setLocalAuthCredentials(identifier: identifer, password: password)
```

and then on subsequent sign ins, you can access those credentials via:
```
let creds = try Clerk.LocalAuth.getLocalAuthCredentials()
try await SignIn.create(strategy: .identifier(creds.identifier, password: creds.password))
```
