### ISSUE TITLE
Two errors on build after update to 0.29.0

### ISSUE THREAD

**Issue by semirteskeredzic** [clerk/clerk-ios#74]
Hi,

I am getting these errors on build after updating package to 0.29.0:

/SourcePackages/checkouts/clerk-ios/Sources/API/Utils/DependencyContainer.swift:45:1 **Inheritance from non-protocol type 'any AutoRegistering'**

/SourcePackages/checkouts/clerk-ios/Sources/API/Utils/DependencyContainer.swift:45:22 **Unknown attribute 'retroactive'**

I am using:
Xcode Version 15.4 (15F31d)
iOS Deployment target 17.0

**Comment by mikepitre** [comment]
Thanks for the report @semirteskeredzic  Looks like a use of @retroactive snuck in there. You can use Xcode 16 as a workaround until this is fixed tomorrow.

**Comment by mikepitre** [comment]
This should be fixed in [`0.29.1`](https://github.com/clerk/clerk-ios/releases/tag/0.29.1)
