### ISSUE TITLE
Question: how to obtain user's organization memberships

### ISSUE THREAD

**Issue by michaelaflores** [clerk/clerk-ios#96]
I see there is a `User` struct, and similar to elsewhere the organization memberships are not a property on this object. That makes sense, but I also don't see a way in the SDK to get those memberships other than maybe using the V1Endpoints but I can't see how to access that from the docs. Is this supported?

**Comment by mikepitre** [comment]
Hey @michaelaflores, orgs aren't yet supported in the iOS SDK, but they are one of the next few items in the roadmap.

**Comment by michaelaflores** [comment]
@mikepitre ty!
